version: '3'
services:
    rskj:
        build:
            context: '.'
            args:
                - rskj_codename=IRIS
                - rskj_version=3.3.0
                - working_branch=IRIS-3.3.0
        container_name: rsk-node
        image: rskj:latest
        command: --regtest
        ports:
            - '127.0.0.1:4444:4444'
            - '127.0.0.1:4445:4445'
        networks:
            - 'rif-relay-testing'

networks:
    rif-relay-testing:
        external: true
